#!/usr/bin/env bash
# make nginx list to 80 it is be def
# to avoid any erros link enabled to available
# another way to include available insted of en in config
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
