#!/usr/bin/env bash
# configures an Ubuntu server with 127.0.0.2 as local host and fb to 8.8.8.8

# first by cping the file to avoid any errors then using sed -i to edit

cp /etc/hosts ~/hosts.new
index=$(grep -n "127.0.0.1	localhost" ~/hosts.new | cut -d: -f1 | head -n "1")

sed -i -e "s/127.0.0.1\(.*localhost\)/127.0.0.2\1/" -e "${index}i8.8.8.8	facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
